os: linux
dist: xenial
language: cpp

compiler:
  - clang
  - gcc

#script:
#  - cmake .
#  - cmake --buld .

stages:
  - build
  - test

jobs:
  include:
    - stage: build
      script:
        - cmake .
        - cmake --build .
    - stage: test
      script: ctest -R Tests