dist: bionic
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - 'ubuntu-toolchain-r-test'
          packages:
            - gcc-10
            - g++-10
      env:
        - CC=gcc-10
        - CXX=g++-10

    - os: linux
      compiler: clang

script:
  - cmake .
  - cmake --build .
  - ctest