dist: bionic
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-10
      - g++-10
env:
  - CC=gcc-10
  - CXX=g++-10

script:
  - cmake .
  - cmake --build .
  - ctest