dist: bionic
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-10
            - g++-10
      env:
        - CC=gcc-10
        - CXX=g++-10

    - os: linux
      compiler: clang
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-12 main
        - sudo apt-get -y install clang-12
      env:
        - CC=clang-10
        - CXX=clang++-10

script:
  - cmake .
  - cmake --build .
  - ctest