dist: bionic
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-10
            - g++-10
      env:
        - CC=gcc-10
        - CXX=g++-10

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-10
          packages:
            - clang-10
      env:
        - CC=clang-10
        - CXX=clang++-10

script:
  - cmake .
  - cmake --build .
  - ctest